#!/bin/bash

PG_DATA_DIR="/home/$USER/postgresql_data"
PG_ROLE="postgres"
PG_DB="harbor"
PG_PASSWORD="put password in here"
echo "Creating PostgreSQL data directory at $PG_DATA_DIR"
mkdir -p "$PG_DATA_DIR"
chown -R "$USER:$USER" "$PG_DATA_DIR"
chmod 700 "$PG_DATA_DIR"
echo "Initializing PostgreSQL database in $PG_DATA_DIR"
sudo -u "$USER"initdb -D "$PG_DATA_DIR"
echo "Starting PostgreSQL server"
sudo -u "$USER" pg_ctl -D "$PG_DATA_DIR" -l logfile start
echo "Creating 'postgres' role"
sudo -u "$USER" psql -c "CREATE ROLE $PG_ROLE WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$PG_PASSWORD';"
echo "Creating 'harbor' database"
sudo -u "$USER" psql -c "CREATE DATABASE $PG_DB;"
echo "Configuring pg_hba.conf for non-local connections"
PG_HBA_CONF="$PG_DATA_DIR/pg_hba.conf"
sudo sed -i "/# IPv4 local connections:/a host    all             all             0.0.0.0/0            md5" "$PG_HBA_CONF"
sudo sed -i "/# IPv6 local connections:/a host    all             all             ::/0                 md5" "$PG_HBA_CONF"
PG_CONF="$PG_DATA_DIR/postgresql.conf"
sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" "$PG_CONF"
echo "Reloading PostgreSQL configuration"
sudo -u "$USER" pg_ctl -D "$PG_DATA_DIR" reload
echo "Listing all databases and connecting to 'harbor'"
sudo -u "$USER" psql -c "\l"
sudo -u "$USER" psql -c "\c $PG_DB"
echo "PostgreSQL setup complete."
